### ISSUE TITLE
Pagination Issue Filtering Enum

### ISSUE THREAD

**Issue by mydeadlyvenoms** [omnifaces/optimusfaces#10]
Today I found out that filtering on enum columns (normal columns but field is `@Enumerated`) does not update the Pagination.
Both searches do not have any matches and do not show any rows.

# "Non Enum" Column 
![image](https://user-images.githubusercontent.com/4450605/35725609-3b46632c-0802-11e8-84e6-5a8f8b3da0d9.png)

# "Enum" Column
![image](https://user-images.githubusercontent.com/4450605/35725602-2f2cd5c6-0802-11e8-8b10-86a848c01729.png)

**Comment by BalusC** [comment]
Reproduced.

**Comment by mydeadlyvenoms** [comment]
I can confirm the implemented solution works fine!
As usual, thank you very much :-)
