### ISSUE TITLE
Show Enum via toString() instead of name()

### ISSUE THREAD

**Issue by mydeadlyvenoms** [omnifaces/optimusfaces#11]
When using columns implemented as enums, filtering applies to the `toString()` value, which is great. Wouldn't it make sense to also use the `toString()` value of an enum instead of `name()` within the view? I know a possible "workaround" is to create a custom facelet tag.

**Comment by BalusC** [comment]
Clever.

**Comment by mydeadlyvenoms** [comment]
Hi @BalusC 
I can confirm it works for `Enum`(s), can you also enable it for `@ElementCollection`(s) containing Enum(s)?
Thank you very much for your help!

**Comment by mydeadlyvenoms** [comment]
@BalusC can we also reopen this one (`@ElementCollection` is missing)?

**Comment by BalusC** [comment]
Fixed.

**Comment by mydeadlyvenoms** [comment]
Same here, I can confirm that it works. 👍
