### ISSUE TITLE
Ability to add additional buttons via f:facet

### ISSUE THREAD

**Issue by mydeadlyvenoms** [omnifaces/optimusfaces#14]
OptimusFaces allows to add additional buttons to the `op:dataTable` header via `<f:facet name="header">...</f:facet>`. It would be nice if the additional buttons are placed inside the resulting `<div class="ui-datatable-actions ui-helper-clearfix">...</div>`. Currently the resulting table header looks like the following:

![image](https://user-images.githubusercontent.com/4450605/36675816-51da9354-1b0a-11e8-9e95-c4ba6f3b10da.png)

**Comment by BalusC** [comment]
You can now use `<ui:define name="actions">` for this instead of `<f:facet name="header">`.

**Comment by mydeadlyvenoms** [comment]
Hi @BalusC 
Thank you for the additional feature!
There is still a line break due to the `<div>...</div>` created by the `toggler`. When changing the `<div>...</div>` to` <span>...</span>` the line break is gone. Please let me know if I can further assist!

**Comment by mydeadlyvenoms** [comment]
@BalusC can we reopen this one?

**Comment by BalusC** [comment]
Sorted out now.

**Comment by mydeadlyvenoms** [comment]
Thank you very much, I can confirm that it works.
