### ISSUE TITLE
multiViewState via f:attribute does not work

### ISSUE THREAD

**Issue by mydeadlyvenoms** [omnifaces/optimusfaces#15]
Hi @BalusC 
Today I tried to use the `multiViewState` option of PrimeFaces like the following:
`<f:attribute name="multiViewState" value="#{true}" />`

The cookies are getting created but the dataTables state does not survive a page reload.

**Comment by BalusC** [comment]
Duplicates https://github.com/primefaces/primefaces/issues/2155

**Comment by mydeadlyvenoms** [comment]
Ouch! Didn't see this one, thank you.
