### ISSUE TITLE
DataExporter Pre/PostProcessor

### ISSUE THREAD

**Issue by mydeadlyvenoms** [omnifaces/optimusfaces#20]
Hi @BalusC 
Is there a way to enable p:dataExporter customizations? Due to the abstraction of the dataExporter it is currently not possible to pass attributes / values or am I missing something?

Thank you very much for your help!

**Comment by BalusC** [comment]
```
<op:dataTable ... 
    exportPreProcessor="#{bean.preProcess}"
    exportPostProcessor="#{bean.postProcess}"
>
```
