### ISSUE TITLE
Support for Upcoming PrimeFaces 8.0 Release

### ISSUE THREAD

**Issue by mydeadlyvenoms** [omnifaces/optimusfaces#28]
I did a few tests using the Omni*-Suite and the upcoming PrimeFaces 8.0 (currently in RC2) release. Seems like most of the feature do still work however, filtering and sorting seems to be broken due to the changes within PrimeFaces (see https://github.com/primefaces/primefaces/wiki/Migration-Guide).

**Comment by open-gdsn** [comment]
8.0 has been released. Let me see what I can come up with as a patch... Nice homework during https://www.youtube.com/watch?v=uo7HB-slsm4

**Comment by kukel** [comment]
I (Same user as @open-gdsn, different account) have made some small changes to `LazyPagedDataModel` so OptimusFaces works with PF 8.0... I still have to find some creative solution so it can still work with older PF versions. Reason for this is that I want to provide more features that can be of interest to users of older PF versions as well and I don't think OptimusFaces (or I for that matter) want to support two branches. With the FilterMeta change in PrimeFaces, OptimusFaces can drop some code, but just for PF 8... So for now I'll leave that in. Pull requests coming up coming days.

See https://github.com/kukel/optimusfaces/commit/8fb22efe2802c5d5f923fdaa6be54e7e5fb1fc82

**Comment by kukel** [comment]
Seems to be sorting is not yet fully working. Some thing to look into tomorrow

**Comment by kukel** [comment]
Weird, sorting seems to be working now... Without any changes... will investigate more

**Comment by BalusC** [comment]
I'll also take a look :+1:

**Comment by BalusC** [comment]
I'll switch IT tests to use PF 8.0

**Comment by BalusC** [comment]
IT tests have been switched to use PF 8.0 :+1:

**Comment by mydeadlyvenoms** [comment]
@BalusC nice one, seems to work fine! :-)
