### ISSUE TITLE
Column Toggler, Exporter and Full-Text Search aren't placed inside the table header

### ISSUE THREAD

**Issue by mydeadlyvenoms** [omnifaces/optimusfaces#5]
Hi @BalusC 
I just tried to combine `searchable="true"` und `exportable="true"`.
The resulting UI components aren't placed inside the table header (next to each other).
I am not sure if this is a real bug.

![image](https://user-images.githubusercontent.com/4450605/31426609-557dbac6-ae64-11e7-8c17-757339181b02.png)

Anyway, thank you for your time.

**Comment by BalusC** [comment]
OptimusFaces doesn't ship with any CSS. It's is up to you. You can find the necessary class names in PagedDataModel javadoc.

In this specific case, following should get you started:

```
.ui-datatable-search, .ui-datatable-export { display: inline-block; }
```

**Comment by mydeadlyvenoms** [comment]
Thank you for your response, okay I see but shouldn't these UI controls be part of the table header (`<f:facet name="header">...</f:facet>`)? Normally I would use something like the following.

```
<f:facet name="header">                              
  <p:commandButton id="toggler" type="button" value="Columns" icon="fa fa-columns" />
  <p:columnToggler datasource="blubTable" trigger="toggler" />
</f:facet>
```

**Comment by BalusC** [comment]
Agreed. It was outside the header for historic reasons which isn't valid anymore these days.

**Comment by mydeadlyvenoms** [comment]
Looks way better now. :-)
